[build]
  command = "pnpm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "pnpm run dev:vite"
  targetPort = 5173
  port = 8888
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200